---
#- hosts: all
#  roles:
#  - mount-disk
#  - jdk
#
#- hosts: all
#  roles:
#  - cp-hosts
#
#
#- hosts: localhost
#  roles:
#  - mysql-init
#  - ops
#
#- hosts: zk
#  roles:
#  - zookeeper-cluster
#
#- hosts: zk
#  roles:
#  - zookeeper-alone

- hosts: hdfs
  roles:
  - hdfs

- hosts: flume
  roles:
  - flume

- hosts: spark_scala
  roles:
  - spark-scala

- hosts: server
  roles:
  - game-server

- hosts: gateway
  roles:
  - game-gateway

- hosts: gm
  roles:
  - tomcat
