---
- name: 部署游戏服
  file:
    path: "{{ s_dir }}"
    state: directory

- name: 下载压缩包
  unarchive:
    src: "{{ s_pkg }}"
    dest: "{{ s_dir }}"
    remote_src: True

- name: zk连接配置文件
  template:
    src: appContext.xml.j2
    dest: "{{ s_dir }}/config/appContext.xml"
  tags: 
    - change_config

- name: 数据连接配置文件
  template:
    src: deploy.properties.j2
    dest: "{{ s_dir }}/config/deploy.properties"
  tags: 
    - change_config

- name: log4j配置文件
  template:
    src: log4j.properties.j2
    dest: "{{ s_dir }}/config/log4j.properties"
  tags: 
    - change_config

- name: 添加定制启动脚本
  template:
    src: srun.sh.j2
    dest: "{{ s_dir }}/srun.sh"
    mode: 0744
  tags:
    - change_config

- name: 添加java线程dump
  template:
    src: dumpjava.j2
    dest: /usr/local/bin/dumpjava
    mode: 0744

- name: 添加管理程序
  copy: 
    src: game
    dest: /usr/local/bin/game
    mode: 0744
  tags:
    - run_script

- name: 创建备份目录
  file:
    path: "{{ backup_dir }}"
    state: directory

- name: 添加快捷路径
  shell: "echo 'cd {{ s_dir }}' >> /etc/profile"
  tags:
    - link_path

- name: 添加清除日定时任务
  template:
    src: root.j2
    dest: /var/spool/cron/root
    mode: 0600
  tags:
    - crontab

- name: 添加解析
  blockinfile:
    dest: /etc/hosts
    block: |
      127.0.0.1        {{ ansible_hostname }}

