---
- name: 安装agent
  yum:
    name: zabbix22-agent
    state: present

- name: 配置
  template:
    src: zabbix_agentd.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf
  tags:
    - change_config

- name: 启动agent
  shell: zabbix_agentd

