---
- name: 安装Flume
  file:
    path: "{{ bigdata_dir }}/flume"
    state: directory 

- name: 下载解压源码包
  unarchive:
    src: "{{ flume_pkg }}"
    dest: "{{ bigdata_dir }}/flume"
    validate_certs: no
    remote_src: True

- name: 配置Flume.conf
  template:
    src: flume.conf.j2
    dest: "{{ flume_dir }}/conf/flume.conf"
  tags:
    - change_config

- name: 增加flume启动程序
  template:
    src: flume.j2
    dest: /usr/local/bin/flume
    mode: 0744 
  tags:
    - run_script

- name: 添加快捷路径
  shell: "echo 'cd {{ bigdata_dir }}'>> /etc/profile "
  tags: 
    - link_path

- name: 启动flume
  shell: flume start
  register: flume_status

- name: flume状态
  debug:
    msg: "{{ flume_status.stdout }}"

- name: 添加解析
  blockinfile:
    dest: /etc/hosts
    block: |
      127.0.0.1        {{ ansible_hostname }}
